### ISSUE TITLE
Lock up

### ISSUE THREAD

**Issue by napanorton** [repetier/Repetier-Host-Mac#17]
I've been running v0.31 and it seems that after about a while, usually more than an hour (not consistent however), the print stops and the it seems the host "locks up". Every once and a while it will make it through a 2 hour print.  I can click the disconnect button and the EStop button and disconnect, but if I try things like pause, heat on/off etc. Nothing seems to happen. I'm guessing something is wrong in the USB comm area. 

I have no idea how to compile this with debugging, but am willing to help feedback more complete info if you can tell me how. For the moment, I'm trying to run v0.30 to see if works more reliably.

**Comment by repetier** [comment]
In such cases you should always look at the log to see what is happening. Also look at the status bar. If you are seeing x command waiting, there is a problem with communication that prevents the host from sending more commands.

With some boards/usb cables the usb connection can hang up, which causes the same error. If that happens there is nothing you can do about on the software side, because it is a hardware problem.

I'm doubting 0.30 will give other results - I havent changed the communication system since it is running reliable (at least for other user). So perhaps the log gives you some hints or you should try an other (better, shorter) usb cable. The printer causes much noise and an unstable usb connection can be the result with the wrong circumstances.

If you are using Repetier-Firmware you could do the following tests, to check if it is a hardware problem.
Test 1:
Send M111 S20 and print file. You printer will do nothing except acknowledge the received line. Print is very fast, because the lines are not really executed. No noise.

Test 2:
Enable Dry run and print file. Your printer makes all moves, except heating extruder/bed and no extrudes. Ideal for tests. Noise only from 2 steppers, no high currents.

Test 3:
Normal print. Ok we know what the result is.

**Comment by napanorton** [comment]
I'll try what you've suggested. It does say x command waiting. As a comparison, I've got a Solidoodle and when using the supplied software (pronterface), I don't see this problem (at least not yet). I'll let you know what I find.

-- David

**Comment by napanorton** [comment]
Just attempted test 1 both by typing m111 s20 into the G-Code field in the print panel, then clicking Run and by adding m111 s20 as the first line of the Gcode file. Both resulted in the printer attempting to print the object - i.e. motors moved and it extruded.

What am I missing?

-- David

**Comment by napanorton** [comment]
I just realized I'm using the Marlin v1.0 firmware modified for Solidoodle. That must be the problem.   I'll have to look at what differences are.

-- david

**Comment by repetier** [comment]
These two debug modes are unique to repetier-firmware. So the only option left is to look at the log for some hints what the problem is. It could also be a problem with the printer connection settings. Pronterface uses what the host names ping-pong mode. Perhaps this helps.

BTW, in a few minutes I publish 0.32 for download.

**Comment by napanorton** [comment]
I just uploaded the repeater firmware and now the M111 codes are working. Looks like it's going to take an hour or so to do the s20 run. Thanks for all the help.  I'll update when I have more info.

-- D

**Comment by napanorton** [comment]
Well I uploaded the Repetier and after several hours of tinkering, got the configuration.h set up for the Solidoodle. So far my communication problems have disappeared, so I guess it was an issue with the old firmware. Thanks for all the help. Awesome project! I hope to keep using Repetier as the shipping Solidoodle SW leaves a lot to be desired.
